# Generated by Django 5.1.3 on 2025-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='license_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='profile_image',
            field=models.CharField(max_length=100),
        ),
    ]
