# Generated by Django 3.2.25 on 2025-03-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_serviceorder_status'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('remaining_services', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscriptionplan')),
            ],
        ),
    ]
