# Generated by Django 3.2.25 on 2025-03-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businesssubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessSubscription',
        ),
    ]
