# Generated by Django 3.2.25 on 2025-04-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
        ('business', '0003_delete_businesssubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myadmin.login'),
        ),
    ]
