# Generated by Django 3.2.25 on 2025-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='num_bags',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
