# Generated by Django 5.1.3 on 2025-01-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_subscriptionplan_serviceorder_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='user',
            new_name='USER',
        ),
    ]
