# Generated by Django 5.1.3 on 2025-01-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_serviceorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='user',
            new_name='USER',
        ),
    ]
