# Generated by Django 5.1.3 on 2025-01-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_logisticsassignment_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsassignment',
            name='delivery_status',
            field=models.CharField(choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='Not Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'in progress'), ('Washing', 'washing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
