# Generated by Django 5.1.3 on 2025-01-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_logisticsassignment_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('processing', 'Processing'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
