# Generated by Django 5.1.3 on 2025-01-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_bags',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logisticsassignment',
            name='delivery_status',
            field=models.CharField(choices=[('not_assigned', 'Not Assigned'), ('assigned', 'Assigned'), ('pickuped', 'Pickuped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='Not Assigned', max_length=20),
        ),
        migrations.CreateModel(
            name='LaundryBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.PositiveIntegerField()),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(max_length=100)),
                ('assigned', models.BooleanField(default=False)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='LAUNDRYBAG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.laundrybag'),
        ),
    ]
