# Generated by Django 5.1.3 on 2025-01-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_num_bags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybag',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickup_assigned', 'Pickup Assigned'), ('in_progress', 'in progress'), ('Washing', 'washing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
