# Generated by Django 5.1.3 on 2025-01-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_laundrybag_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='USER',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
