# Generated by Django 5.1.3 on 2025-01-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_serviceorder_user_serviceorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='User',
            new_name='USER',
        ),
    ]
