# Generated by Django 5.1.3 on 2025-01-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_user_serviceorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='LAUNDRYBAG',
        ),
    ]
