# Generated by Django 5.1.3 on 2025-01-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_serviceorder_laundrybag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundrybag',
            name='bag_number',
        ),
        migrations.AddField(
            model_name='laundrybag',
            name='preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
