# Generated by Django 3.2.25 on 2025-03-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_laundrybag_bag_number_laundrybag_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickup_assigned', 'Pickup Assigned'), ('in_progress', 'in progress'), ('Washing', 'washing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
