# Generated by Django 3.2.25 on 2025-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20250331_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cloth_density',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price_per_kg',
        ),
        migrations.AddField(
            model_name='payment',
            name='cloth_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_per_cloth',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
