# Generated by Django 3.2.25 on 2025-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20250331_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
