# Generated by Django 3.2.25 on 2025-03-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_delete_businesssubscription'),
        ('user', '0018_subscriptionplan_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='BUSINESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service_for',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('business', 'Business')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
