# Generated by Django 3.2.25 on 2025-04-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_billitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cloth_count',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price_per_cloth',
        ),
    ]
