# Generated by Django 3.2.25 on 2025-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20250401_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybag',
            name='assigned',
            field=models.BooleanField(default=True),
        ),
    ]
