# Generated by Django 3.2.25 on 2025-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_laundrybag_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybag',
            name='assigned',
            field=models.BooleanField(default=True),
        ),
    ]
