# Generated by Django 3.2.25 on 2025-04-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_num_bags'),
        ('user', '0024_alter_laundrybag_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrybag',
            name='BUSINESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='laundrybag',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
