# Generated by Django 5.2.5 on 2026-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20250414_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.FloatField(help_text='Capacity in kg')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight of laundry in kg'),
        ),
    ]
