# Generated by Django 5.2.5 on 2026-02-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_machine_serviceorder_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
