# Generated by Django 5.2.5 on 2026-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybag',
            name='qr_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
